openapi: 3.1.0
info:
  title: Farcaster API V2
  version: "2.20.0"
  description: The Farcaster API allows you to interact with the Farcaster protocol.
  contact:
    name: Neynar
    url: https://neynar.com/
    email: team@neynar.com
servers:
  - url: https://api.neynar.com/v2

security:
  - ApiKeyAuth: []

components:
  securitySchemes:
    ApiKeyAuth:
      $ref: "./components/securitySchemes/api_key.yaml#/ApiKeyAuth"
  parameters:
    NeynarExperimentalHeader:
      $ref: "./components/parameters/common.yaml#/NeynarExperimentalHeader"
  responses:
    401Response:
      $ref: "./components/responses/error.yaml#/401Response"
    404Response:
      $ref: "./components/responses/error.yaml#/404Response"
    400Response:
      $ref: "./components/responses/error.yaml#/400Response"
    403Response:
      $ref: "./components/responses/error.yaml#/403Response"
    500Response:
      $ref: "./components/responses/error.yaml#/500Response"
  schemas:
    Address:
      $ref: "./components/schemas/common.yaml#/Address"
    SolAddress:
      $ref: "./components/schemas/common.yaml#/SolAddress"
    Fid:
      $ref: "./components/schemas/common.yaml#/Fid"
    ChannelId:
      $ref: "./components/schemas/common.yaml#/ChannelId"
    SignerUUID:
      $ref: "./components/schemas/common.yaml#/SignerUUID"
    Timestamp:
      $ref: "./components/schemas/common.yaml#/Timestamp"
    Ed25519PublicKey:
      $ref: "./components/schemas/common.yaml#/Ed25519PublicKey"
    NextCursor:
      type: string
    ErrorRes:
      $ref: "./components/schemas/error.yaml#/ErrorRes"
    UserFIDResponse:
      $ref: "./components/schemas/user.yaml#/UserFIDResponse"
    Signer:
      $ref: "./components/schemas/signer.yaml#/Signer"
    CastParamType:
      $ref: "./components/schemas/cast.yaml#/CastParamType"
    ReplyDepth:
      $ref: "./components/schemas/cast.yaml#/ReplyDepth"
    CastConversationResponse:
      $ref: "./components/schemas/cast.yaml#/CastConversationResponse"
    FeedTrendingProvider:
      $ref: "./components/schemas/feed.yaml#/FeedTrendingProvider"
    FeedResponse:
      $ref: "./components/schemas/feed.yaml#/FeedResponse"
    ReactionType:
      $ref: "./components/schemas/reaction.yaml#/ReactionType"
    ReactionsType:
      $ref: "./components/schemas/reaction.yaml#/ReactionsType"
    ReactionsResponse:
      $ref: "./components/schemas/reaction.yaml#/ReactionsResponse"
    ChannelResponse:
      $ref: "./components/schemas/channel.yaml#/ChannelResponse"
    ValidateFrameReqBody:
      $ref: "./components/schemas/frame.yaml#/ValidateFrameReqBody"
    ValidateFrameResponse:
      $ref: "./components/schemas/frame.yaml#/ValidateFrameResponse"

tags:
  - name: User
    description: Operations related to user
  - name: Signer
    description: Operations related to signer
  - name: Cast
    description: Operations related to cast
  - name: Feed
    description: Operations related to feed
  - name: Reaction
    description: Operations related to reaction
  - name: Channel
    description: Operations related to channels
  - name: Frame
    description: Operations related to frames

paths:
  /farcaster/user/fid:
    $ref: "./paths/user/fid.yaml"
  /farcaster/signer/status:
    $ref: "./paths/signer/status.yaml"
  /farcaster/cast/conversation:
    $ref: "./paths/cast/conversation.yaml"
  /farcaster/feed/trending:
    $ref: "./paths/feed/trending.yaml"
  /farcaster/reactions:
    $ref: "./paths/reaction/reactions.yaml"
  /farcaster/channel:
    $ref: "./paths/channel/info.yaml"
  /farcaster/frame/validate:
    $ref: "./paths/frame/validate.yaml"
