name: Update Docs (Mintlify)

on:
  push:
    branches:
      - main

jobs:
  update-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context # Makes it much easier to retrospectively debug all sorts of workflow issues. Does NOT expose secrets.
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
        
      - name: Generate Neynar CI Bot token
        id: generate-token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ secrets.NEYNAR_CI_BOT_APP_ID }}
          private-key: ${{ secrets.NEYNAR_CI_BOT_PRIVATE_KEY }}
          owner: 'neynarxyz'
          repositories: 'docs'

      - name: Checkout OAS repository
        uses: actions/checkout@v3

      - name: Checkout docs repository
        uses: actions/checkout@v3
        with:
          repository: "neynarxyz/docs.git"
          ref: "main"
          path: "docs"
          token: ${{ steps.generate-token.outputs.token }}
          persist-credentials: true

      - name: Copy updated YAML files to docs repository
        run: |
          cp src/hub-api/spec.yaml ../docs/openapi/hub-api/openapi.yaml
          cp src/api/spec.yaml ../docs/openapi/api/openapi.yaml

      - name: Commit and push changes
        run: |
          cd docs

          # Set Git config using OAS commit author
          git config user.name "Neynar CI Bot"
          git config user.email "team@neynar.com"

          # Stage and commit any changes
          if git diff --quiet; then
            echo "No changes to commit."
            exit 0
          fi
          git add .
          git commit -m "GitHub action: copy OpenAPI YAML files from OAS repository"

          # Push changes directly to main
          git push origin main
        shell: bash
